title: DPMD
default_lang: en
author:
  name: Administrator
  email: hadron@crabston.dev
taxonomies:
  - category
  - tag
  - month
  - author
  - filter
metadata:
  description: 'Hadron ist ein Grav Theme und Skeleton, das für Einsteiger als Vorlage für Website uns Webshops dient, aber auch für Profis als Basis für komplexe Projekte genutzt werden kann.'
  keywords: 'grav, theme, skeleton, hadron, website, webshop'
  enabled: 'true'
  format: short
  size: '300'
  delimiter: '==='
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
